### ISSUE TITLE
Create base components

### ISSUE THREAD

**Issue by giteshk11** [pcl-labs/browtricks-ui-components#1]
Identify and create base components that would be reused across the whole UI e.g. Buttons, Inputs, etc.

- [x] Typography like headers, labels, etc (No need to create components but relevant config should be present in tailwind config)
- [x] Buttons with variations e.g. Button with icon on right, left, and button with loading spinner.
- [x] Input fields with variations and validation.
- [ ] Dialogs/Modals
- [x] Mobile/Desktop Side Nav
- [x] Top Header with a dropdown on the right side.

Figma: [https://www.figma.com/file/kwIHq0NTQUDBryrkZVN1ap/browtricks-cms?node-id=915%3A1500&t=KyXE7VMEsBV6L8TG-0](https://www.figma.com/file/kwIHq0NTQUDBryrkZVN1ap/browtricks-cms?node-id=915%3A1500&t=KyXE7VMEsBV6L8TG-0)

**Note**:  Please start marking the component as done in this issue when a component code is reviewed and merged into the main branch.

**Comment by kshekh** [comment]
Hello @giteshk11
The typography for header, labels, etc.. already exists and we do not need to put it into a tailwind.config otherwise it will work as traditional css
I'm working to create components for form elements e.g. Buttons, Inputs.
Dialogs/models will be built in milestone 2nd
The side Navbar has been already created
The top header has been created with a dropdown you can check by clink user icon/photo
